CREATE TABLE category(
  id SERIAL PRIMARY KEY NOT NULL ,
  name TEXT DEFAULT ''
);

CREATE TABLE good(
  id SERIAL PRIMARY KEY NOT NULL ,
  title TEXT DEFAULT '',
  description TEXT DEFAULT ''
);

CREATE TABLE attachment(
  id SERIAL PRIMARY KEY NOT NULL ,
  good_id INTEGER NOT NULL ,
  url TEXT NOT NULL ,
  type TEXT NOT NULL,
  FOREIGN KEY (good_id) REFERENCES  good(id)
  MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE category_to_good(
  id SERIAL PRIMARY KEY NOT NULL ,
  category_id INTEGER NOT NULL ,
  good_id INTEGER NOT NULL,

  FOREIGN KEY (category_id) REFERENCES  category(id)
  MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY (good_id) REFERENCES  good(id)
  MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);


